export default {
    'GET_RECIPES': 'GET_RECIPES',
    'GET_RECIPES_SUCCESS': 'GET_RECIPES_SUCCESS',
    'GET_RECIPES_ERROR': 'GET_RECIPES_ERROR',
  
    //chef
    'GET_CHEFS': 'GET_CHEFS',
    'GET_CHEFS_SUCCESS': 'GET_CHEFS_SUCCESS',
    'GET_CHEFS_ERROR': 'GET_CHEFS_ERROR',

     //ingredientes
     'GET_INGREDIENTS': 'GET_INGREDIENTS',
     'GET_INGREDIENTS_SUCCESS': 'GET_INGREDIENTS_SUCCESS',
     'GET_INGREDIENTS_ERROR': 'GET_INGREDIENTS_ERROR',
  }